FROM ubuntu:latest

WORKDIR /todo-app

COPY todo-app ./
COPY web ./web

ARG TODO_PORT
ARG TODO_DBFILE
ARG TODO_PASSWORD
ARG TODO_SECRET

ENV TODO_PORT=${TODO_PORT}
ENV TODO_DBFILE=${TODO_DBFILE}
ENV TODO_PASSWORD=${TODO_PASSWORD}
ENV TODO_SECRET=${TODO_SECRET}

EXPOSE ${TODO_PORT} 

CMD [ "./todo-app" ]
